package main

import "testing"

const INPUT string = `T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........`
const EXPECT int = 9

func Test(t *testing.T) {
	output := partTwo(INPUT)
	if output != EXPECT {
		t.Fatalf("Expected: %d Got: %d", EXPECT, output)
	}
}

func Test2(t *testing.T) {
	const INPUT string = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`
	const EXPECT int = 34

	output := partTwo(INPUT)
	if output != EXPECT {
		t.Fatalf("Expected: %d Got: %d", EXPECT, output)
	}
}

